# Generated by Django 5.2.17 on 2026-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
