# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analitica", "0001_initial"),
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandadiaria",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demanda_diaria",
                to="catalogo.producto",
            ),
        ),
        migrations.AddIndex(
            model_name="demandadiaria",
            index=models.Index(
                fields=["producto", "fecha"], name="analitica_d_product_b649f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="demandadiaria",
            unique_together={("producto", "fecha")},
        ),
    ]
