# Generated by Django 5.2.17 on 2026-09-27 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0002_initial"),
        ("catalogo", "0004_unidades_iniciales"),
        ("core", "0004_configuracionnegocio_alfa_suavizado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temporada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("inicio_mes", models.PositiveSmallIntegerField()),
                ("inicio_dia", models.PositiveSmallIntegerField()),
                ("fin_mes", models.PositiveSmallIntegerField()),
                ("fin_dia", models.PositiveSmallIntegerField()),
                (
                    "factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = aplica a todos los productos",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.categoria",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporadas",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["inicio_mes", "inicio_dia"],
            },
        ),
        migrations.CreateModel(
            name="RegistroPronostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                ("pronosticado", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "real",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronosticos",
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-desde"],
                "unique_together": {("producto", "desde")},
            },
        ),
    ]
