# Generated by Django 5.2.17 on 2026-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0003_temporada_registropronostico"),
    ]

    operations = [
        migrations.AddField(
            model_name="registropronostico",
            name="dias_agotado",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Días del período sin stock (venta censurada)"
            ),
        ),
    ]
