# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Negocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "nit",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIT / documento"
                    ),
                ),
                (
                    "giro",
                    models.CharField(
                        choices=[
                            ("MINIMERCADO", "Tienda / minimercado"),
                            ("ROPA", "Ropa y calzado"),
                            ("BELLEZA", "Belleza y cosméticos"),
                            ("FARMACIA", "Farmacia / droguería"),
                            ("RESTAURANTE", "Restaurante / comidas"),
                            ("GENERICO", "Otro (genérico)"),
                        ],
                        default="GENERICO",
                        max_length=20,
                    ),
                ),
                ("moneda", models.CharField(default="COP", max_length=3)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("direccion", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("usa_vencimientos", models.BooleanField(default=False)),
                ("usa_lotes", models.BooleanField(default=False)),
                (
                    "usa_variantes",
                    models.BooleanField(default=False, help_text="Talla, color, tono…"),
                ),
                (
                    "permite_fracciones",
                    models.BooleanField(
                        default=False, help_text="Vender 0,5 kg, 1,25 L…"
                    ),
                ),
                ("usa_temporadas", models.BooleanField(default=False)),
                ("dias_vencimiento_rojo", models.PositiveIntegerField(default=7)),
                ("dias_vencimiento_amarillo", models.PositiveIntegerField(default=30)),
                (
                    "dias_sin_movimiento",
                    models.PositiveIntegerField(
                        default=45, help_text="Para baja rotación"
                    ),
                ),
                (
                    "dias_exceso",
                    models.PositiveIntegerField(
                        default=90, help_text="Cobertura que se considera exceso"
                    ),
                ),
                (
                    "horizonte_compra_dias",
                    models.PositiveIntegerField(
                        default=7, help_text="Días que debe cubrir un pedido"
                    ),
                ),
                (
                    "tiempo_entrega_defecto",
                    models.PositiveIntegerField(
                        default=3, help_text="Si el producto no tiene proveedor"
                    ),
                ),
                (
                    "negocio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("accion", models.CharField(max_length=50)),
                ("entidad", models.CharField(max_length=50)),
                ("entidad_id", models.CharField(max_length=40)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditoria",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
