# Generated by Django 5.2.17 on 2026-09-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="resumen_por_correo",
            field=models.BooleanField(
                default=True,
                help_text="Enviar cada mañana las alertas críticas a los administradores",
            ),
        ),
    ]
