# Generated by Django 5.2.17 on 2026-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_configuracionnegocio_resumen_por_correo"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="alfa_suavizado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                help_text="Qué tanto pesan las ventas recientes (0.1 = estable, 0.6 = reacciona rápido)",
                max_digits=3,
            ),
        ),
    ]
