# Generated by Django 5.2.17 on 2026-09-27 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_configuracionnegocio_alfa_suavizado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("GRATIS", "Gratis"),
                            ("EMPRENDEDOR", "Emprendedor"),
                            ("NEGOCIO", "Negocio"),
                        ],
                        default="GRATIS",
                        max_length=12,
                    ),
                ),
                ("prueba_hasta", models.DateField(blank=True, null=True)),
                ("pagado_hasta", models.DateField(blank=True, null=True)),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Pagos recibidos, acuerdos comerciales…"
                    ),
                ),
                (
                    "negocio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripcion",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
