# Generated by Django 5.2.17 on 2026-09-27 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_suscripciones_existentes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idea o mejora"),
                            ("ERROR", "Algo no funciona"),
                            ("PREGUNTA", "Pregunta"),
                        ],
                        default="IDEA",
                        max_length=10,
                    ),
                ),
                ("texto", models.TextField(max_length=2000)),
                ("pagina", models.CharField(blank=True, max_length=200)),
                (
                    "calificacion",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1 a 5", null=True
                    ),
                ),
                ("atendido", models.BooleanField(default=False)),
                (
                    "negocio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.negocio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
