# Generated by Django 5.2.17 on 2026-09-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_comentarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="EjecucionTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=60)),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("detalle", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
    ]
