# Generated by Django 5.2.17 on 2026-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_ejecucion_tareas"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="alertas_silenciadas",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="horizonte_automatico",
            field=models.BooleanField(
                default=True,
                help_text="Ajustar el horizonte al ciclo real de compra de cada proveedor (si compras cada 14 días, el pedido cubre 14 días)",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="permite_venta_sin_stock",
            field=models.BooleanField(
                default=True,
                help_text="Si el sistema dice 0 pero el producto está en la estantería, se vende igual y queda un ajuste para revisar",
            ),
        ),
    ]
