# Generated by Django 5.2.17 on 2026-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_fase8"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="encuesta_satisfaccion",
            field=models.BooleanField(
                default=True, help_text="Mostrar la encuesta en el comprobante"
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="fidelizacion_activa",
            field=models.BooleanField(
                default=True, help_text="Los clientes registrados acumulan puntos"
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="nivel_frecuente_compras",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Compras en los últimos 90 días para ser cliente frecuente",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="nivel_vip_monto",
            field=models.PositiveIntegerField(
                default=500000,
                help_text="Compras (en pesos) en los últimos 90 días para ser VIP",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="pesos_por_punto",
            field=models.PositiveIntegerField(
                default=1000, help_text="Cada cuántos pesos de compra se gana 1 punto"
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="puntos_minimos_canje",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="valor_punto",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Cuántos pesos de descuento vale 1 punto al canjear",
            ),
        ),
    ]
