# Generated by Django 5.2.17 on 2026-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_fase9"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="giro",
            field=models.CharField(
                choices=[
                    ("MINIMERCADO", "Tienda / minimercado"),
                    ("ROPA", "Ropa y calzado"),
                    ("BELLEZA", "Belleza y cosméticos"),
                    ("FARMACIA", "Farmacia / droguería"),
                    ("RESTAURANTE", "Restaurante / comidas"),
                    ("BAR", "Bar / gastrobar"),
                    ("DISCOTECA", "Discoteca"),
                    ("BAR_DISCOTECA", "Bar-discoteca"),
                    ("GENERICO", "Otro (genérico)"),
                ],
                default="GENERICO",
                max_length=20,
            ),
        ),
    ]
