# Generated by Django 5.2.17 on 2026-09-29 07:25

import apps.core.imagenes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_giro_vape"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="color_principal",
            field=models.CharField(
                default="#1f7a4d",
                help_text="Botones, menú y enlaces",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Usa un color como #1f7a4d."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="letra_grande",
            field=models.BooleanField(
                default=False, help_text="Letra más grande en toda la aplicación"
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Aparece en la barra de arriba y en el comprobante",
                null=True,
                upload_to=apps.core.imagenes.ruta_logo,
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="tema",
            field=models.CharField(
                choices=[
                    ("AUTO", "Automático (como el celular)"),
                    ("CLARO", "Claro"),
                    ("OSCURO", "Oscuro"),
                ],
                default="AUTO",
                max_length=6,
            ),
        ),
    ]
