# Generated by Django 5.2.17 on 2026-09-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_apariencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="api",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="limite_productos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="limite_usuarios",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="modulos_apagados",
            field=models.JSONField(
                blank=True, default=list, help_text="Módulos que este negocio no tiene"
            ),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="reportes_pdf",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
