# Generated by Django 5.2.17 on 2026-10-02 04:18

import django.core.validators
from django.db import migrations, models


def nuevo_color(apps, schema_editor):
    """Los negocios que seguían con el verde de fábrica pasan al nuevo color de la marca (los que eligieron otro, no)."""
    apps.get_model("core", "ConfiguracionNegocio").objects.filter(color_principal__iexact="#1f7a4d").update(
        color_principal="#0f5b5e")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_plan_a_la_medida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="color_principal",
            field=models.CharField(
                default="#0f5b5e",
                help_text="Botones, menú y enlaces",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Usa un color como #1f7a4d."
                    )
                ],
            ),
        ),
        migrations.RunPython(nuevo_color, migrations.RunPython.noop),
    ]
