# Generated by Django 5.2.17 on 2026-10-02 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_color_petroleo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="color_principal",
            field=models.CharField(
                default="#0f5b5e",
                help_text="Botones, menú y enlaces",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Usa un color como #0f5b5e."
                    )
                ],
            ),
        ),
    ]
