# Generated by Django 5.2.17 on 2026-09-28 05:51

import apps.clientes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0007_fase9"),
        ("core", "0010_fase9"),
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120)),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Celular / WhatsApp"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("documento", models.CharField(blank=True, max_length=20)),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True,
                        help_text="Para saludarlo en su cumpleaños",
                        null=True,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Preferencias: talla, tono, alergias a ingredientes…",
                    ),
                ),
                (
                    "acepta_datos",
                    models.BooleanField(
                        default=False,
                        verbose_name="Autorizó el tratamiento de sus datos",
                    ),
                ),
                (
                    "acepta_ofertas",
                    models.BooleanField(
                        default=False,
                        verbose_name="Acepta recibir ofertas por WhatsApp",
                    ),
                ),
                ("fecha_autorizacion", models.DateTimeField(blank=True, null=True)),
                ("puntos", models.IntegerField(default=0)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("NUEVO", "Nuevo"),
                            ("FRECUENTE", "Frecuente"),
                            ("VIP", "VIP"),
                        ],
                        default="NUEVO",
                        max_length=10,
                    ),
                ),
                ("n_compras", models.PositiveIntegerField(default=0)),
                (
                    "total_compras",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("primera_compra", models.DateTimeField(blank=True, null=True)),
                (
                    "ultima_compra",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Encuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.clientes.models._token, max_length=24, unique=True
                    ),
                ),
                (
                    "calificacion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comentario", models.TextField(blank=True, max_length=1000)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                (
                    "respondida",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encuestas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuestas",
                        to="core.negocio",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuesta",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "ordering": ["-respondida", "-creada"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoPuntos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GANADOS", "Ganados por compra"),
                            ("CANJEADOS", "Canjeados"),
                            ("DEVUELTOS", "Reversados por anulación"),
                            ("AJUSTE", "Ajuste manual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "puntos",
                    models.IntegerField(help_text="Positivo suma, negativo resta"),
                ),
                ("saldo", models.IntegerField()),
                ("fecha", models.DateTimeField(db_index=True)),
                ("motivo", models.CharField(blank=True, max_length=200)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_puntos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=120)),
                (
                    "descuento_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Descuento %"
                    ),
                ),
                (
                    "segmento",
                    models.CharField(
                        choices=[
                            ("TODOS", "Todos (también clientes sin registrar)"),
                            (
                                "COMPRADORES",
                                "Quienes han comprado ese producto o categoría",
                            ),
                            ("VIP", "Clientes VIP"),
                            ("FRECUENTES", "Clientes frecuentes y VIP"),
                            ("EN_RIESGO", "Clientes que dejaron de venir"),
                            ("NUEVOS", "Clientes nuevos"),
                            ("CUMPLEANOS", "Cumpleañeros del mes"),
                        ],
                        default="TODOS",
                        max_length=12,
                    ),
                ),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                (
                    "mensaje",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de WhatsApp. Puedes usar {nombre}, {puntos}, {negocio}, {descuento}, {hasta}",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("origen", models.CharField(default="MANUAL", max_length=10)),
                ("clave_sugerencia", models.CharField(blank=True, max_length=80)),
                (
                    "razon",
                    models.TextField(
                        blank=True, help_text="Por qué el sistema la sugirió"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.categoria",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="core.negocio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = aplica a toda la compra (o a la categoría)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-desde", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EnvioOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas_recibidas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="clientes.oferta",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["negocio", "activo"], name="clientes_cl_negocio_f8c7bc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telefono", ""), _negated=True),
                fields=("negocio", "telefono"),
                name="cliente_telefono_unico_por_negocio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enviooferta",
            unique_together={("oferta", "cliente")},
        ),
    ]
