# Generated by Django 5.2.17 on 2026-09-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="mayor_edad_verificado",
            field=models.BooleanField(
                default=False,
                verbose_name="Se verificó con cédula que es mayor de edad",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="referido_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente que lo trajo (gana puntos en su primera compra)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referidos",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="movimientopuntos",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("GANADOS", "Ganados por compra"),
                    ("CANJEADOS", "Canjeados"),
                    ("DEVUELTOS", "Reversados por anulación"),
                    ("AJUSTE", "Ajuste manual"),
                    ("BONO", "Bono (visitas, referidos, grupos)"),
                ],
                max_length=10,
            ),
        ),
    ]
