# Generated by Django 5.2.17 on 2026-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConteoFisico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_PROCESO", "En proceso"),
                            ("PENDIENTE", "Pendiente de aprobación"),
                            ("APROBADO", "Aprobado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="EN_PROCESO",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetalleConteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_sistema", models.DecimalField(decimal_places=3, max_digits=12)),
                ("stock_contado", models.DecimalField(decimal_places=3, max_digits=12)),
                ("motivo", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(blank=True, max_length=40)),
                (
                    "fecha_vencimiento",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ["fecha_vencimiento", "creado"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA_INICIAL", "Inventario inicial"),
                            ("ENTRADA_COMPRA", "Compra a proveedor"),
                            ("ENTRADA_DEVOLUCION_CLIENTE", "Devolución de cliente"),
                            ("ENTRADA_AJUSTE", "Ajuste positivo"),
                            ("SALIDA_VENTA", "Venta"),
                            ("SALIDA_DANADO", "Producto dañado"),
                            ("SALIDA_VENCIDO", "Producto vencido"),
                            ("SALIDA_DEVOLUCION_PROVEEDOR", "Devolución al proveedor"),
                            ("SALIDA_AJUSTE", "Ajuste negativo"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3, help_text="Siempre positiva", max_digits=12
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_resultante",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("fecha", models.DateTimeField(db_index=True)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                ("referencia_tipo", models.CharField(blank=True, max_length=30)),
                ("referencia_id", models.PositiveIntegerField(blank=True, null=True)),
                ("marcado_anomalo", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
    ]
