# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0002_initial"),
        ("core", "0002_initial"),
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conteofisico",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conteofisico",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.negocio"
            ),
        ),
        migrations.AddField(
            model_name="conteofisico",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="detalleconteo",
            name="conteo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="inventario.conteofisico",
            ),
        ),
        migrations.AddField(
            model_name="detalleconteo",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalogo.producto"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lotes",
                to="catalogo.producto",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.lote",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="core.negocio",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="catalogo.producto",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(
                fields=["producto", "fecha"], name="inventario__product_07599f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(
                fields=["negocio", "tipo", "fecha"],
                name="inventario__negocio_40d34b_idx",
            ),
        ),
    ]
