# Generated by Django 5.2.17 on 2026-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimiento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA_INICIAL", "Inventario inicial"),
                    ("ENTRADA_COMPRA", "Compra a proveedor"),
                    ("ENTRADA_DEVOLUCION_CLIENTE", "Devolución de cliente"),
                    ("ENTRADA_AJUSTE", "Ajuste positivo"),
                    ("SALIDA_VENTA", "Venta"),
                    ("SALIDA_DANADO", "Producto dañado"),
                    ("SALIDA_VENCIDO", "Producto vencido"),
                    ("SALIDA_DEVOLUCION_PROVEEDOR", "Devolución al proveedor"),
                    ("SALIDA_AJUSTE", "Ajuste negativo"),
                    (
                        "SALIDA_CONSUMO_INTERNO",
                        "Consumo interno (uso en servicios o cocina)",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
