# Generated by Django 5.2.17 on 2026-09-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_fase9"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimiento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA_INICIAL", "Inventario inicial (con lo que empezó)"),
                    ("ENTRADA_COMPRA", "Llegó mercancía del proveedor"),
                    ("ENTRADA_DEVOLUCION_CLIENTE", "Un cliente la devolvió"),
                    ("ENTRADA_AJUSTE", "Corrección: había más de lo anotado"),
                    ("ENTRADA_PRODUCCION", "Se produjo aquí con insumos"),
                    ("SALIDA_VENTA", "Se vendió"),
                    ("SALIDA_DANADO", "Se dañó o se rompió"),
                    ("SALIDA_VENCIDO", "Se venció"),
                    ("SALIDA_DEVOLUCION_PROVEEDOR", "Se devolvió al proveedor"),
                    (
                        "SALIDA_AJUSTE",
                        "Corrección: había menos de lo anotado (faltante)",
                    ),
                    (
                        "SALIDA_CONSUMO_INTERNO",
                        "Consumo interno (cocina, servicios o la casa)",
                    ),
                    (
                        "SALIDA_INSUMO",
                        "Se usó para preparar (tragos, cócteles o platos)",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
