# Generated by Django 5.2.17 on 2026-09-28 22:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0008_unidad_botella"),
        ("clientes", "0002_fase10"),
        ("core", "0011_fase10"),
        ("ventas", "0003_fase10"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotellaGuardada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restante_pct",
                    models.PositiveSmallIntegerField(help_text="Cuánto quedó (en %)"),
                ),
                ("guardada", models.DateTimeField(default=django.utils.timezone.now)),
                ("vence", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("GUARDADA", "Guardada"),
                            ("RETIRADA", "Retirada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="GUARDADA",
                        max_length=10,
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, help_text="Estante / casillero", max_length=40
                    ),
                ),
                ("retirada", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="botellas_guardadas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="botellas_guardadas",
                        to="core.negocio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["vence"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionNocturna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "hora_corte",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="Hora en que termina la noche (0 a 12)"
                    ),
                ),
                (
                    "aforo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Capacidad máxima de personas (0 = sin control)",
                    ),
                ),
                (
                    "cover_valor",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Valor de la entrada por persona (0 = sin cover)",
                    ),
                ),
                (
                    "cover_consumible",
                    models.BooleanField(
                        default=True,
                        help_text="El cover se descuenta de lo que consuma",
                    ),
                ),
                (
                    "cover_gratis_desde",
                    models.CharField(
                        choices=[
                            ("NINGUNO", "Nadie (todos pagan)"),
                            ("VIP", "Clientes VIP"),
                            ("FRECUENTE", "Frecuentes y VIP"),
                        ],
                        default="VIP",
                        max_length=10,
                    ),
                ),
                (
                    "acompanantes_gratis",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Acompañantes que entran gratis con el cliente VIP o frecuente (el resto del grupo paga)",
                    ),
                ),
                (
                    "propina_sugerida_pct",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Propina voluntaria sugerida al cobrar. Ley 1935 de 2018: máximo el 10 % antes de impuestos y el cliente decide si la acepta, la cambia o no la da",
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "grupo_minimo_personas",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="Desde cuántas personas es grupo"
                    ),
                ),
                (
                    "grupo_descuento_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Descuento en la cuenta de un grupo",
                        max_digits=5,
                    ),
                ),
                (
                    "grupo_puntos_por_asistente",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Puntos para quien organiza el grupo por cada persona que llegó",
                    ),
                ),
                (
                    "visitas_para_bono",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Cada cuántas noches de visita hay bono"
                    ),
                ),
                ("puntos_bono_visita", models.PositiveIntegerField(default=100)),
                (
                    "puntos_por_referido",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Para quien trae a un cliente nuevo, cuando este hace su primera compra",
                    ),
                ),
                (
                    "botella_guardada_dias",
                    models.PositiveSmallIntegerField(
                        default=60, help_text="Días que se guarda una botella"
                    ),
                ),
                (
                    "exigir_mayoria_edad",
                    models.BooleanField(
                        default=True,
                        help_text="Registrar clientes solo si se verificó la cédula (Ley 124 de 1994)",
                    ),
                ),
                (
                    "negocio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nocturno",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Ej.: «Barra – camisa roja»",
                        max_length=80,
                    ),
                ),
                ("personas", models.PositiveSmallIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "Abierta"),
                            ("COBRADA", "Cobrada"),
                            ("ANULADA", "Anulada"),
                        ],
                        db_index=True,
                        default="ABIERTA",
                        max_length=10,
                    ),
                ),
                ("noche", models.DateField(db_index=True)),
                (
                    "credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cover consumible y anticipos: se descuentan al cobrar",
                        max_digits=12,
                    ),
                ),
                (
                    "credito_usado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "consumo_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento_grupo_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("cerrada", models.DateTimeField(blank=True, null=True)),
                (
                    "abierta_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuentas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="ItemCuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "agregado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Define si aplica happy hour",
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=120)),
                (
                    "cortesia",
                    models.BooleanField(
                        default=False,
                        help_text="Invitación de la casa (precio 0, sí descuenta inventario)",
                    ),
                ),
                (
                    "agregado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nocturno.cuenta",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Venta con la que se cobró (vacío = pendiente)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "ordering": ["agregado", "id"],
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                (
                    "zona",
                    models.CharField(
                        choices=[
                            ("BARRA", "Barra"),
                            ("SALON", "Salón"),
                            ("VIP", "VIP"),
                            ("TERRAZA", "Terraza"),
                        ],
                        default="SALON",
                        max_length=10,
                    ),
                ),
                ("capacidad", models.PositiveSmallIntegerField(default=4)),
                (
                    "consumo_minimo",
                    models.PositiveIntegerField(
                        default=0, help_text="Para mesas VIP (0 = sin mínimo)"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesas",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["zona", "nombre"],
                "unique_together": {("negocio", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="cuenta",
            name="mesa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuentas",
                to="nocturno.mesa",
            ),
        ),
        migrations.CreateModel(
            name="PrecioEspecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Happy hour, Jueves de rumba", max_length=80
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Descuento %"),
                            ("DOS_POR_UNO", "2 × 1"),
                            ("PRECIO_FIJO", "Precio fijo"),
                        ],
                        default="PORCENTAJE",
                        max_length=12,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje o precio fijo (no aplica al 2×1)",
                        max_digits=12,
                    ),
                ),
                (
                    "dias",
                    models.JSONField(default=list, help_text="0 = lunes … 6 = domingo"),
                ),
                ("hora_inicio", models.TimeField()),
                (
                    "hora_fin",
                    models.TimeField(
                        help_text="Puede pasar la medianoche (ej.: 22:00 a 01:00)"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalogo.categoria",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_especiales",
                        to="core.negocio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MESA", "Mesa"),
                            ("GRUPO", "Grupo"),
                            ("CUMPLEANOS", "Cumpleaños"),
                            ("LISTA", "Lista de invitados (promotor)"),
                        ],
                        default="MESA",
                        max_length=12,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="A nombre de quién", max_length=120),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "promotor",
                    models.CharField(
                        blank=True,
                        help_text="Relacionista / promotor que la trajo",
                        max_length=80,
                    ),
                ),
                ("fecha", models.DateField(help_text="Noche de la reserva")),
                ("hora", models.TimeField(blank=True, null=True)),
                ("personas", models.PositiveSmallIntegerField(default=2)),
                (
                    "consumo_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "anticipo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("LLEGO", "Llegó"),
                            ("NO_LLEGO", "No llegó"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quien reserva u organiza",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="nocturno.mesa",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora", "id"],
            },
        ),
        migrations.CreateModel(
            name="Invitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("llego", models.BooleanField(default=False)),
                ("llegada", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitados",
                        to="nocturno.reserva",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noche", models.DateField(db_index=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("personas", models.PositiveSmallIntegerField(default=1)),
                (
                    "valor_por_persona",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("personas_gratis", models.PositiveSmallIntegerField(default=0)),
                ("consumible", models.BooleanField(default=True)),
                ("motivo_gratis", models.CharField(blank=True, max_length=80)),
                ("medio_pago", models.CharField(default="EFECTIVO", max_length=15)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingresos",
                        to="nocturno.cuenta",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingresos",
                        to="core.negocio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ventas.venta",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingresos",
                        to="nocturno.reserva",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="cuenta",
            name="reserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuentas",
                to="nocturno.reserva",
            ),
        ),
    ]
