# Generated by Django 5.2.17 on 2026-09-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_plan_a_la_medida"),
        ("nocturno", "0001_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="mesero",
            field=models.ForeignKey(
                blank=True,
                help_text="Quién atiende la mesa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuentas_atendidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="pide_cuenta",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuándo el mesero avisó que quieren pagar",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AsignacionMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noche", models.DateField(db_index=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="nocturno.mesa",
                    ),
                ),
                (
                    "mesero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_mesa",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["mesa__zona", "mesa__nombre"],
                "unique_together": {("mesa", "noche")},
            },
        ),
    ]
