# Generated by Django 5.2.17 on 2026-10-01 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_plan_a_la_medida"),
        ("nocturno", "0002_mesas_por_mesero"),
        ("ventas", "0003_fase10"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaMesero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lo que entra a la caja",
                        max_digits=12,
                    ),
                ),
                (
                    "paga_con",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Billete con que pagó el cliente",
                        max_digits=12,
                    ),
                ),
                (
                    "vueltas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("creado", models.DateTimeField(default=django.utils.timezone.now)),
                ("recibida", models.DateTimeField(blank=True, null=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="nocturno.cuenta",
                    ),
                ),
                (
                    "mesero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_mesero",
                        to="core.negocio",
                    ),
                ),
                (
                    "recibida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "ordering": ["recibida", "-creado"],
            },
        ),
    ]
