# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("core", "0001_initial"),
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecomendacionCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("cantidad_sugerida", models.PositiveIntegerField()),
                (
                    "demanda_diaria",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "stock_seguridad",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("tiempo_entrega", models.DecimalField(decimal_places=1, max_digits=6)),
                (
                    "stock_al_calcular",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("explicacion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADA", "Convertida en orden"),
                            ("DESCARTADA", "Descartada"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendaciones",
                        to="core.negocio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendaciones",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
