# Generated by Django 5.2.17 on 2026-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recomendaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recomendacioncompra",
            name="motivo_descarte",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="recomendacioncompra",
            name="temporada",
            field=models.CharField(
                blank=True,
                help_text="Temporada considerada en el cálculo",
                max_length=80,
            ),
        ),
    ]
