# Generated by Django 5.2.17 on 2026-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AGOTADO", "Producto agotado"),
                            ("STOCK_CRITICO", "Stock crítico"),
                            ("STOCK_BAJO", "Stock bajo"),
                            ("RIESGO_AGOTAMIENTO", "Riesgo de agotamiento"),
                            ("VENCIMIENTO", "Próximo a vencer"),
                            ("VENCIDO", "Producto vencido"),
                            ("BAJA_ROTACION", "Baja rotación"),
                            ("EXCESO", "Exceso de inventario"),
                            ("ANOMALIA", "Movimiento inusual"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "severidad",
                    models.IntegerField(
                        choices=[
                            (1, "🔵 Información"),
                            (2, "🟡 Revisar"),
                            (3, "🔴 Actuar"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "Abierta"),
                            ("VISTA", "Vista"),
                            ("RESUELTA", "Resuelta"),
                            ("DESCARTADA", "Descartada"),
                        ],
                        default="ABIERTA",
                        max_length=12,
                    ),
                ),
                ("mensaje", models.CharField(max_length=300)),
                ("accion_sugerida", models.CharField(blank=True, max_length=200)),
                ("datos", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-severidad", "-creado"],
            },
        ),
    ]
