# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alertas", "0001_initial"),
        ("catalogo", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas",
                to="core.negocio",
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas",
                to="catalogo.producto",
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["negocio", "estado", "severidad"],
                name="alertas_ale_negocio_c2c985_idx",
            ),
        ),
    ]
