# Generated by Django 5.2.17 on 2026-09-27 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="nota",
            field=models.CharField(
                blank=True,
                help_text="Justificación al resolver o descartar",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="resuelta_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
