# Generated by Django 5.2.17 on 2026-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas", "0003_alerta_nota_alerta_resuelta_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("AGOTADO", "Producto agotado"),
                    ("STOCK_CRITICO", "Stock crítico"),
                    ("STOCK_BAJO", "Stock bajo"),
                    ("RIESGO_AGOTAMIENTO", "Riesgo de agotamiento"),
                    ("VENCIMIENTO", "Próximo a vencer"),
                    ("VENCIDO", "Producto vencido"),
                    ("BAJA_ROTACION", "Baja rotación"),
                    ("EXCESO", "Exceso de inventario"),
                    ("ANOMALIA", "Movimiento inusual"),
                    ("VENTA_SIN_STOCK", "Venta sin stock registrado"),
                ],
                max_length=25,
            ),
        ),
    ]
