# Generated by Django 5.2.17 on 2026-10-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas", "0004_fase8"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="severidad",
            field=models.IntegerField(
                choices=[(1, "Información"), (2, "Revisar"), (3, "Actuar")], default=2
            ),
        ),
    ]
