# Generated by Django 5.2.17 on 2026-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtributoPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEXTO", "Texto"),
                            ("NUMERO", "Número"),
                            ("OPCION", "Lista de opciones"),
                        ],
                        default="TEXTO",
                        max_length=10,
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(
                        blank=True, default=list, help_text='Ej: ["S", "M", "L"]'
                    ),
                ),
                ("obligatorio", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=40, verbose_name="Código / SKU")),
                (
                    "codigo_barras",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_compra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_venta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=3, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "stock_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "atributos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Valores de atributos personalizados",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, unique=True)),
                ("abreviatura", models.CharField(max_length=10)),
                ("permite_decimales", models.BooleanField(default=False)),
            ],
        ),
    ]
