# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("core", "0001_initial"),
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="core.negocio",
            ),
        ),
        migrations.AddField(
            model_name="atributopersonalizado",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atributos",
                to="catalogo.categoria",
            ),
        ),
        migrations.AddField(
            model_name="marca",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marcas",
                to="core.negocio",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogo.categoria",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogo.marca",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="core.negocio",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="proveedores.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.unidadmedida",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoria",
            unique_together={("negocio", "nombre")},
        ),
        migrations.AlterUniqueTogether(
            name="atributopersonalizado",
            unique_together={("categoria", "nombre")},
        ),
        migrations.AlterUniqueTogether(
            name="marca",
            unique_together={("negocio", "nombre")},
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["negocio", "activo"], name="catalogo_pr_negocio_2ec97f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producto",
            unique_together={("negocio", "sku")},
        ),
    ]
