# Generated by Django 5.2.17 on 2026-09-27 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="es_agrupador",
            field=models.BooleanField(
                default=False,
                help_text="Producto padre de variantes; no se vende ni maneja stock",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variantes",
                to="catalogo.producto",
            ),
        ),
    ]
