# Generated by Django 5.2.17 on 2026-09-27 15:16

import apps.core.imagenes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_unidades_iniciales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.imagenes.ruta_imagen_producto
            ),
        ),
    ]
