# Generated by Django 5.2.17 on 2026-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_imagen_por_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="vida_util_dias",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cuántos días dura el producto desde que llega. Limita el pedido sugerido y fecha los lotes solo",
                null=True,
                verbose_name="Vida útil (días)",
            ),
        ),
    ]
