# Generated by Django 5.2.17 on 2026-09-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_fase8"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PRODUCTO", "Producto (se vende y tiene stock)"),
                    ("INSUMO", "Insumo (se compra y se gasta; no se vende)"),
                    (
                        "PREPARADO",
                        "Preparado o servicio (se vende; gasta insumos de su receta)",
                    ),
                ],
                db_index=True,
                default="PRODUCTO",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RecetaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Por cada unidad del producto",
                        max_digits=12,
                    ),
                ),
                (
                    "merma_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lo que se pierde al preparar (cáscaras, recortes…)",
                        max_digits=5,
                        verbose_name="Merma %",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usado_en",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receta",
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["insumo__nombre"],
                "unique_together": {("producto", "insumo")},
            },
        ),
    ]
