# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada al proveedor"),
                            ("CONFIRMADA", "Confirmada por el proveedor"),
                            ("PARCIAL", "Recibida parcialmente"),
                            ("RECIBIDA", "Recibida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_recepcion", models.DateTimeField(blank=True, null=True)),
                (
                    "dias_entrega",
                    models.PositiveIntegerField(
                        blank=True, help_text="Calculado al recibir", null=True
                    ),
                ),
                ("numero_factura", models.CharField(blank=True, max_length=40)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_pedida",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "cantidad_recibida",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.producto",
                    ),
                ),
            ],
        ),
    ]
