# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("recomendaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleordencompra",
            name="recomendacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recomendaciones.recomendacioncompra",
            ),
        ),
    ]
