# Generated by Django 5.2.17 on 2026-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="es_compra_directa",
            field=models.BooleanField(
                default=False, help_text="Factura registrada sin orden previa"
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="fecha_esperada",
            field=models.DateField(blank=True, null=True),
        ),
    ]
