# Generated by Django 5.2.17 on 2026-09-27 21:19

import apps.compras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0004_fecha_esperada_compra_directa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="factura_imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.compras.models.ruta_factura,
                verbose_name="Foto de la factura",
            ),
        ),
    ]
