# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("nit", models.CharField(blank=True, max_length=30)),
                ("contacto", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tiempo_entrega_dias",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Estimado inicial; se recalcula con las entregas reales",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ProductoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tiempo_entrega_dias",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "multiplo_empaque",
                    models.PositiveIntegerField(
                        default=1, help_text="Ej: se compra por cajas de 12"
                    ),
                ),
                ("codigo_proveedor", models.CharField(blank=True, max_length=40)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "unique_together": {("proveedor", "producto")},
            },
        ),
    ]
