# Generated by Django 5.2.17 on 2026-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="pin",
            field=models.CharField(
                blank=True,
                help_text="PIN cifrado para cambiar de usuario en un equipo compartido",
                max_length=128,
            ),
        ),
    ]
