# Generated by Django 5.2.17 on 2026-09-30 20:27

from django.db import migrations, models


def meseros(apps, schema_editor):
    """Los usuarios que se crearon como «vendedor» pero son meseros (…-meseroN) pasan al rol Mesero."""
    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario.objects.filter(rol="VENDEDOR", username__regex=r"-mesero[0-9]+$").update(rol="MESERO")


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_fase8"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="areas",
            field=models.JSONField(
                blank=True,
                help_text="Qué partes del sistema ve. Vacío = las de su rol",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("CAJERO", "Cajero"),
                    ("MESERO", "Mesero"),
                    ("VENDEDOR", "Vendedor"),
                    ("INVENTARIO", "Bodega / inventario"),
                ],
                default="VENDEDOR",
                max_length=12,
            ),
        ),
        migrations.RunPython(meseros, migrations.RunPython.noop),
    ]
