# Generated by Django 5.2.17 on 2026-09-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_inicial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="oferta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clientes.oferta",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="cliente_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="descuento_puntos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="venta",
            name="oferta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="clientes.oferta",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="puntos_canjeados",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venta",
            name="puntos_ganados",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
