# Generated by Django 5.2.17 on 2026-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_fase9"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="promocion",
            field=models.CharField(
                blank=True,
                help_text="Happy hour, cortesía, oferta, grupo…",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="pagado_con_credito",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cover consumible o anticipo de reserva aplicado",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="propina",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Voluntaria; no es venta",
                max_digits=12,
            ),
        ),
    ]
